### PR TITLE
Use Tipsy redirect script

### PR DESCRIPTION
**Pull request by tbranyen**
This changes over to using the MIT Tipsy server for script redirection.  We are not able to use querystrings for redirection, it must be part of the URL pathname.  I've noticed that MIT's servers decode the URL encoding and interpret the slashes incorrectly (as they are part of a pathname).   So I do not think this will work as-is.  Might need to replace `/` with a different character.

So basically:

Works:

``` url
http://tipsy.csail.mit.edu/redirect/chrome-extension
```

Doesn't work:

``` url
http://tipsy.csail.mit.edu/redirect/chrome-extension%3A%2F%2Ftest%2F
```

### CODE REVIEW

**Comment by karger** [comment]
tim, if you can clarify the problem with mit decoding, I can talk to the 
sysadmins about fixing it.

**Comment by tbranyen** [comment]
@karger I added an example to the above comment.  I hope that helps!

**Comment by karger** [comment]
Time, do we have web standards documentation which shows that this 
behavior is incorrect?

**Comment by tbranyen** [comment]
Best I could find is: http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.2

But this states the contrary to what we need
> The Request-URI is transmitted in the format specified in section 3.2.1. If the Request-URI is encoded using the "% HEX HEX" encoding [42], the origin server MUST decode the Request-URI in order to properly interpret the request. Servers SHOULD respond to invalid Request-URIs with an appropriate status code.

What I'll do is replace the `/` character with a `$` since that symbol does not exist in our extension URL.  When it comes time to actually redirect in the PHP script, I'll swap back the `/`.

**Comment by karger** [comment]
yeah, if our server is working to spec, we probably won't have much luck 
getting csail to change their server.

**Comment by tbranyen** [comment]
This latest commit works great for me using that replace technique.

**Pull request merged**
