### PR TITLE
Firefox support is out-of-scope

### PR DESCRIPTION
**Pull request by tbranyen**
As we can see from this PR, the Firefox support takes up a huge chunk of
code and cognitive overhead. We should remove this, focus on the Chrome
extension, and work on Firefox support again once they complete their
new approach using Chrome's API.

Only thing left is cleaning out the `docs/modules` references.

### CODE REVIEW

**Comment by karger** [comment]
I agree, let's drop ff support for now.
But, I'm surprised your pr is generating merge conflicts---aren't you working off master?  Did we scramble things somewhere?

**Comment by tbranyen** [comment]
@karger whoops, I had merged two PRs earlier. Forgot to rebase :roll_eyes: whoops! I'll push up a fix PR in a moment.

**Comment by karger** [comment]
OK.  Note that I contacted Philippe at the same time, and he's also pushing, so some care needed....

**Comment by tbranyen** [comment]
Ah okay, can you ask to please push to a separate branch if possible? If not, if he could email me the patches that would work as well. I don't want to put too much pressure on him, especially since he's off the project and I had merged two PRs earlier which may complicate his push.

**Comment by tbranyen** [comment]
That being said, I'll hold off merging this PR until we hear more.

**Comment by da2x** [comment]
The last few versions of Firefox already support WebExtensions (their name for the Chromium Extension API). Packaging requires like two differences in the manifest, and that is about it. The only overhead should be 1) a separate manifest for Firefo’, and 2) testing.

**Comment by tbranyen** [comment]
@da2x definitely! no intentions of dropping support completely, but the original version was limited compared to the Chrome version and required a lot of branching code. If Web Extensions are working well now might be worth another shot. Maybe I can find someone at Mozilla and stop by to try and get this extension working with minimal changes.

Thanks for the heads up!

**Comment by da2x** [comment]
Firefox’s WebExtension support almost exactly the same subset of the Chromium APIs as Vivaldi, Mcirosoft Edge, and Opera. So should be a write-once then add-browser-specific-manifest and finally run-everywhere.

Supported since Firefox 45, actually working properly since Fx48.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by tbranyen** [comment]
@da2x I understand, but do they support all the APIs we need? The link you posted has sections for all the top-level APIs. We'll just need to make sure there are no Chrome incompatibilities for the subset of APIs we use.

Great to hear they've already landed support!

**Comment by tbranyen** [comment]
Merging this, we have a backlog of PRs to close and I want to make sure we don't create a backlog.

**Pull request merged**
