### PR TITLE
Zopfli compressed image resources

### PR DESCRIPTION
**Pull request by da2x**
Lossless image compression. Reduces download size and memory footprint.

For future reference: `ls *.png | xargs -P5 -i% zopflipng --iterations=500 -y '%' '%'`

25–60 % savings.

### CODE REVIEW

**Comment by tbranyen** [comment]
Awesome, I'll merge this since it doesn't change any code.

**Comment by da2x** [comment]
P.S. I did visually inspect the images. No corruption. Not that I’ve ever had a problem with zopflipng except that one time my laptop ran out of battery as the tool was writing the new file to disk. :package:

**Comment by tbranyen** [comment]
Awesome, I skimmed through and they all looked good to me.

**Comment by rht** [comment]
For the record: the space saving is from 527.8 KiB to 397.6 KiB (24.67% overall, uncompressed).

**Pull request merged**
